linters:
  enable-all: true
  disable:
    - exhaustivestruct
    - wsl
    - ireturn
    - nlreturn
    - varnamelen
issues:
  exclude-rules:
    - linters:
        - paralleltest
      text: "does not use range value in test Run"
    - path: _test\.go
      linters:
        - nestif
        - dupl
        - gosec
        - cyclop
        - gochecknoglobals
        - gochecknoinits
        - goerr113
        - nilnil
