linters:
  enable-all: true
  disable:
    - wsl
    - nlreturn
    - ireturn
    - varnamelen
issues:
  exclude-rules:
    - path: ^serialization\.go$
      linters:
        - maligned
    - path: _test\.go$
      linters:
        - funlen
        - maligned
        - cyclop
        - goerr113
        - maintidx
        - gocognit
        - gosec
        - gocyclo
        - nestif
