name: Bump version
on:
  push:
    branches:
      - main
jobs:
  bump-version:
    name: Bump version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: anothrNick/github-tag-action@1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
