name: PR check
on:
  pull_request:
    branches:
      - main
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: golangci/golangci-lint-action
  test:
    name: Test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout
      - uses: actions/setup-go
        with:
          go-version: ^1.16
      - run: go test -race -timeout 1m
